version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: "postgresql://yumi:postgres@db/online_shop"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: yumi
      POSTGRES_PASSWORD: postgres
