version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: "postgresql://yumi:postgres@localhost/online_shop"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: yumi
      POSTGRES_PASSWORD: postgres
