"""empty message

Revision ID: 12d999bd2db9
Revises: 0bc79786751b
Create Date: 2024-01-15 18:55:26.714933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d999bd2db9'
down_revision = '0bc79786751b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
