"""empty message

Revision ID: 1b4f41417b89
Revises: 973d23a7b4b3
Create Date: 2024-01-21 13:40:08.523965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4f41417b89'
down_revision = '973d23a7b4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart', ['quantity'])
    op.create_foreign_key(None, 'orderitms', 'cart', ['quantity'], ['quantity'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitms', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='unique')
    # ### end Alembic commands ###
