"""empty message

Revision ID: 973d23a7b4b3
Revises: 
Create Date: 2024-01-21 13:23:53.365740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973d23a7b4b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orderitms', 'cart', ['quantity'], ['quantity'])
    op.create_unique_constraint('uniq_cart_quantity', 'cart', ['quantity'])
    op.create_foreign_key(None, 'orderitms', 'cart', ['quantity'], ['quantity'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orderitms_quantity_cart', 'orderitms', type_='foreignkey')
    # ### end Alembic commands ###
